#Space_Industry_Analytics_2010_2024.csv


# Import libraries

# Import NumPy for numerical and statistical calculations
import numpy as np

# Import Pandas for data loading and analysis
import pandas as pd

# Import Seaborn for data visualization
import seaborn as sns

# Import Matplotlib for plotting graphs
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

# Convert text labels into numbers
from sklearn.preprocessing import LabelEncoder

# Scale features for KNN
from sklearn.preprocessing import StandardScaler

# Classification Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# Regression Models
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

# Import clustering algorithm
from sklearn.cluster import KMeans

# Import StandardScaler for feature scaling
from sklearn.preprocessing import StandardScaler

# Import Silhouette Score
from sklearn.metrics import silhouette_score

# Evaluation Metrics
from sklearn.metrics import ( accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report)


# Calculate mean revenue, analyze business growth trends, evaluate product launch statistics,
# measure success rates, perform correlation analysis, and execute various mathematical
# and statistical operations using NumPy.


Year,Launches,Successful,Failed,Revenue_USD_M,Budget_Funding_USD_M,Employees,Rockets, Success_Rate  = np.genfromtxt('Data_Sets/Space Industry Analytics/Space_Industry_Analytics_2010_2024.csv', delimiter=',', usecols=(1,2,3,4,5,6,7,8,9), unpack=True, dtype=None,skip_header=1)

print(Year)
print(Launches)
print(Successful)
print(Failed)
print(Revenue_USD_M)
print(Budget_Funding_USD_M)
print(Employees)
print(Rockets)
print(Success_Rate)


# Space_Industry_Analytics_2010_2024  - statistics operations

print("Space_Industry_Analytics Revenue_USD_M mean: " , np.mean(Revenue_USD_M))
print("Space_Industry_Analytics Revenue_USD_M average: " , np.average(Revenue_USD_M))
print("Space_Industry_Analytics Revenue_USD_M std: " , np.std(Revenue_USD_M))
print("Space_Industry_Analytics Revenue_USD_M median: " , np.median(Revenue_USD_M))
print("Space_Industry_Analytics Revenue_USD_M percentile - 25: " , np.percentile(Revenue_USD_M,25))
print("Space_Industry_Analytics Revenue_USD_M percentile  - 75: " , np.percentile(Revenue_USD_M,75))
print("Space_Industry_Analytics Revenue_USD_M percentile  - 3: " , np.percentile(Revenue_USD_M,3))
print("Space_Industry_Analytics Revenue_USD_M min : " , np.min(Revenue_USD_M))
print("Space_Industry_Analytics Revenue_USD_M max : " , np.max(Revenue_USD_M))

# Space_Industry_Analytics Revenue_USD_M  - maths operations

print("Space_Industry_Analytics Revenue_USD_M square: " , np.square(Revenue_USD_M))
print("Space_Industry_Analytics Revenue_USD_M sqrt: " , np.sqrt(Revenue_USD_M))
print("Space_Industry_Analytics Revenue_USD_M pow: " , np.power(Revenue_USD_M,Revenue_USD_M))
print("Space_Industry_Analytics Revenue_USD_M abs: " , np.abs(Revenue_USD_M))

# Calculate the correlation between budget funding and company revenue

correlation_matrix = np.corrcoef(  Budget_Funding_USD_M,Revenue_USD_M)

print("Correlation Matrix:")
print(correlation_matrix)

print("Budget vs Revenue Correlation:",
      correlation_matrix[0,1])


# Now we apply PANDAS; Use Pandas for data manipulation, cleaning, transformation, and exploratory data analysis (EDA) to extract meaningful insights.

# Load dataset into DataFrame
df = pd.read_csv( "Data_Sets/Space Industry Analytics/Space_Industry_Analytics_2010_2024.csv")


# Display first 5 records
print("\nFirst 5 Records")
print(df.head())

# Display last 5 records
print("\nLast 5 Records")
print(df.tail())

# Display dataset shape (rows, columns)
print("\nDataset Shape")
print(df.shape)

# Display column names
print("\nColumn Names")
print(df.columns)

# Display data types
print("\nData Types")
print(df.dtypes)

# Display dataset information
print("\nDataset Information")
df.info()

# Display statistical summary
print("\nStatistical Summary")
print(df.describe())

# Now We Will check DATA QUALITY C

# Count missing values
print("\nMissing Values")
print(df.isnull().sum())

# Count duplicate rows
print("\nDuplicate Rows")
print(df.duplicated().sum())


# Now we will apply FEATURE ENGINEERING

# Revenue generated by each employee

df["Revenue_Per_Employee"] = ( df["Revenue_USD_M"] / df["Employees"])

print("\nRevenue Per Employee Feature")

print( df[["Company", "Revenue_Per_Employee"]].head() )


# Launch success ratio

df["Launch_Success_Ratio"] = ( df["Successful"] / df["Launches"])

print("\nLaunch Success Ratio Feature")

print( df[["Company", "Launch_Success_Ratio"]].head())


# Funding per employee

df["Funding_Per_Employee"] = ( df["Budget_Funding_USD_M"] / df["Employees"])

print("\nFunding Per Employee Feature")

print( df[["Company", "Funding_Per_Employee"]].head())


# Launches per rocket

df["Launches_Per_Rocket"] = ( df["Launches"] / df["Rockets"] )

print("\nLaunches Per Rocket Feature")

print( df[ ["Company", "Launches_Per_Rocket"]].head())


# UNIQUE VALUE ANALYSIS

print("\nUnique Companies")
print(df["Company"].unique())

print("\nTotal Unique Companies")
print(df["Company"].nunique())

print("\nCompany Record Count")
print(df["Company"].value_counts())


# SORTING & FILTERING

print("\nTop Revenue Records")
print( df.sort_values( by="Revenue_USD_M", ascending=False ).head( ) )

print("\nRevenue Greater Than 1000")
print( df[ df["Revenue_USD_M"] > 1000 ] )

print("\nSuccess Rate Above 90%")
print( df[ df["Success_Rate_%"] > 90 ] )


# AGGREGATION ANALYSIS

print("\nTotal Revenue")
print(df["Revenue_USD_M"].sum())

print("\nAverage Revenue")
print(df["Revenue_USD_M"].mean())

print("\nAverage Success Rate")
print(df["Success_Rate_%"].mean())


# CORRELATION ANALYSIS

print("\nCorrelation Matrix")

print( df.corr( numeric_only=True ))


# TOP & LOWEST REVENUE COMPANY

print("\nHighest Revenue Record")

print( df.loc[ df["Revenue_USD_M"].idxmax()])

print("\nLowest Revenue Record")

print( df.loc[ df["Revenue_USD_M"].idxmin() ] )


# YEAR ANALYSIS

print("\nYear Wise Records")

print( df.sort_values( by="Year" ) )


# COMPANY PERFORMANCE SNAPSHOT

print("\nCompany Performance Snapshot")

print( df[
        [
            "Company",
            "Launches",
            "Successful",
            "Failed",
            "Revenue_USD_M",
            "Success_Rate_%"
        ]
    ]
)


# GROUPBY ANALYSIS

print("\nAverage Revenue By Company")

print( df.groupby( "Company")["Revenue_USD_M"].mean() )

print("\nTotal Revenue By Company")

print( df.groupby( "Company" )["Revenue_USD_M"].sum() )

print("\nTotal Launches By Company")

print( df.groupby( "Company" )["Launches"].sum() )

print("\nAverage Success Rate By Company")

print( df.groupby("Company")["Success_Rate_%"].mean() )

print("\nAverage Revenue Per Employee")

print( df.groupby ( "Company" )["Revenue_Per_Employee"].mean() )

print("\nAverage Funding Per Employee")

print( df.groupby( "Company" )["Funding_Per_Employee"].mean())


# Now We will apply Seaborn - To improve chart appearance
sns.set_style("whitegrid")


# VISUALIZATION 1 : CORRELATION HEATMAP

# Create figure size
plt.figure( figsize=(12, 8))

# Create correlation heatmap
sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,          # Show correlation values
    cmap="coolwarm"      # Color theme
)

# Add chart title
plt.title( "Correlation Heatmap")

# Display chart
plt.show()


# VISUALIZATION 2 : REVENUE DISTRIBUTION


plt.figure( figsize=(10, 6) )

sns.histplot( df["Revenue_USD_M"], kde=True )

plt.title( "Revenue Distribution" )

plt.xlabel( "Revenue (Million USD)" )

plt.ylabel( "Frequency" )

plt.show()


# VISUALIZATION 3 : BUDGET VS REVENUE


plt.figure( figsize=(10, 6) )

sns.scatterplot(
    data=df,
    x="Budget_Funding_USD_M",
    y="Revenue_USD_M",
    hue="Company"
)

plt.title( "Budget vs Revenue" )

plt.show()


# VISUALIZATION 4 : COMPANY REVENUE COMPARISON

plt.figure( figsize=(12, 6) )

sns.boxplot(
    data=df,
    x="Company",
    y="Revenue_USD_M"
)

plt.title( "Company Revenue Distribution" )

plt.xticks( rotation=45 )

plt.show()


# VISUALIZATION 5 : REVENUE TREND

plt.figure( figsize=(12, 6) )

sns.lineplot(
    data=df,
    x="Year",
    y="Revenue_USD_M",
    hue="Company"
)

plt.title( "Revenue Trend Over Time" )

plt.show()


# VISUALIZATION 6 : COMPANY RECORD COUNT

plt.figure( figsize=(10, 6))

sns.countplot( data=df,  x="Company" )

plt.title( "Number of Records Per Company" )

plt.xticks( rotation=45 )

plt.show()


# VISUALIZATION 7 : AVERAGE REVENUE BY COMPANY

plt.figure( figsize=(12, 6) )

sns.barplot(
    data=df,
    x="Company",
    y="Revenue_USD_M"
)

plt.title( "Average Revenue By Company")

plt.xticks( rotation=45 )

plt.show()


# VISUALIZATION 8 : PAIRPLOT

sns.pairplot(
    df[
        [
            "Revenue_USD_M",
            "Budget_Funding_USD_M",
            "Employees",
            "Launches",
            "Success_Rate_%"
        ]
    ]
)

plt.show()


# Successful vs Failed Launches

plt.figure( figsize=(10, 6) )

sns.scatterplot(
    data=df,
    x="Successful",
    y="Failed",
    hue="Company"
)

plt.title( "Successful vs Failed Launches" )

plt.show()

# CLASSIFICATION
# FEATURE SELECTION

# X contains input features

X = df[
    [
        "Launches",
        "Successful",
        "Failed",
        "Revenue_USD_M",
        "Budget_Funding_USD_M",
        "Employees",
        "Rockets",
        "Success_Rate_%"
    ]
]

# y contains target variable

y = df["Company"]

# Create Label Encoder object
encoder = LabelEncoder()

# Convert company names into numbers
y_encoded = encoder.fit_transform(y)

print("\nEncoded Companies")

print(y_encoded[:10])

#KNN: Distance Calculations

# Create scaler object
scaler = StandardScaler()

# Standardize features
X_scaled = scaler.fit_transform(X)


# TRAIN TEST SPLIT
# 80% training
# 20% testing

X_train, X_test, y_train, y_test = train_test_split( X_scaled, y_encoded,
    test_size=0.20,
    random_state=42
)

print("\nTraining Records")

print(len(X_train))

print("\nTesting Records")

print(len(X_test))


# LOGISTIC REGRESSION

# Create model
lr_model = LogisticRegression( max_iter=1000 )

# Train model

lr_model.fit( X_train, y_train )

# Make predictions
lr_predictions = lr_model.predict(  X_test )

# Calculate accuracy
lr_accuracy = accuracy_score( y_test, lr_predictions )

print("\nLogistic Regression Accuracy")

print(lr_accuracy)


# DECISION TREE
# Create model

dt_model = DecisionTreeClassifier( random_state=42 )

# Train model
dt_model.fit( X_train, y_train )

# Predict values
dt_predictions = dt_model.predict( X_test )

# Calculate accuracy
dt_accuracy = accuracy_score( y_test, dt_predictions )

print("\nDecision Tree Accuracy")

print(dt_accuracy)


# KNN CLASSIFIER

# Create KNN model
knn_model = KNeighborsClassifier(  n_neighbors=3 )

# Train model
knn_model.fit( X_train, y_train )

# Make predictions
knn_predictions = knn_model.predict( X_test )

# Accuracy
knn_accuracy = accuracy_score( y_test, knn_predictions )

print("\nKNN Accuracy")

print(knn_accuracy)


# RANDOM FOREST CLASSIFIER

# Create Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train model
rf_model.fit( X_train, y_train )

# Make predictions
rf_predictions = rf_model.predict( X_test )

# Accuracy
rf_accuracy = accuracy_score( y_test, rf_predictions )

print("\nRandom Forest Accuracy")

print(rf_accuracy)


# CLASSIFICATION REPORT

print("\nClassification Report")

print( classification_report( y_test, rf_predictions ) )

# MODEL METRICS

print("\nPrecision")

print(  precision_score( y_test, rf_predictions,average="weighted" ) )

print("\nRecall")

print( recall_score(  y_test,  rf_predictions, average="weighted" ) )

print("\nF1 Score")

print(  f1_score( y_test, rf_predictions, average="weighted" ) )


# CONFUSION MATRIX

cm = confusion_matrix( y_test, rf_predictions )

print("\nConfusion Matrix")

print(cm)


# CONFUSION MATRIX HEATMAP

plt.figure(figsize=(8, 6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title( "Random Forest Confusion Matrix")

plt.xlabel( "Predicted")

plt.ylabel( "Actual" )

plt.show()


# MODEL COMPARISON

comparison_df = pd.DataFrame(
    {
        "Model": [
            "Logistic Regression",
            "Decision Tree",
            "KNN",
            "Random Forest"
        ],

        "Accuracy": [
            lr_accuracy,
            dt_accuracy,
            knn_accuracy,
            rf_accuracy
        ]
    }
)

print("\nClassification Model Comparison")

print(comparison_df)


# Classification Insight

print("\nCLASSIFICATION INSIGHTS")

print("""
1. Multiple classification algorithms were tested.

2. Random Forest usually performs best because it combines many trees.

3. KNN performance depends heavily on feature scaling.

4. Decision Tree is easy to interpret but may overfit.

5. Logistic Regression serves as a baseline model.

6. The best model should be selected based on accuracy and F1 score.
""")

# Import Evaluation Metrics
from sklearn.metrics import ( r2_score, mean_absolute_error, mean_squared_error )
 

# FEATURE SELECTION
# Independent Variables (Features)

X = df[
    [
        "Launches",
        "Successful",
        "Failed",
        "Budget_Funding_USD_M",
        "Employees",
        "Rockets",
        "Success_Rate_%"
    ]
]

# Dependent Variable (Target)

y = df["Revenue_USD_M"]


# TRAIN TEST SPLIT
# Split dataset into training (80%) and testing (20%)

X_train, X_test, y_train, y_test = train_test_split( X, y,
    test_size=0.20,
    random_state=42
)

print("\nTraining Records")
print(len(X_train))

print("\nTesting Records")
print(len(X_test))


# LINEAR REGRESSION

# Create Linear Regression model
lr_model = LinearRegression()

# Train model
lr_model.fit(
    X_train,
    y_train
)

# Predict testing data
lr_prediction = lr_model.predict( X_test )

# Calculate R² Score
lr_r2 = r2_score( y_test, lr_prediction )

# Calculate Mean Absolute Error
lr_mae = mean_absolute_error( y_test, lr_prediction)

# Calculate Root Mean Squared Error
lr_rmse = np.sqrt(  mean_squared_error( y_test, lr_prediction ) )

print("\nLinear Regression Results")
print("R² Score :", lr_r2)
print("MAE :", lr_mae)
print("RMSE :", lr_rmse)



# DECISION TREE REGRESSOR

# Create Decision Tree model
dt_model = DecisionTreeRegressor( random_state=42 )

# Train model

dt_model.fit( X_train, y_train )

# Predict testing data
dt_prediction = dt_model.predict( X_test )

# Evaluation Metrics
dt_r2 = r2_score( y_test, dt_prediction )

dt_mae = mean_absolute_error( y_test, dt_prediction )

dt_rmse = np.sqrt( mean_squared_error( y_test, dt_prediction ) )

print("\nDecision Tree Results")
print("R² Score :", dt_r2)
print("MAE :", dt_mae)
print("RMSE :", dt_rmse)


# RANDOM FOREST REGRESSOR
# Create Random Forest model

rf_model = RandomForestRegressor( n_estimators=100, random_state=42 )

# Train model
rf_model.fit( X_train,  y_train )

# Predict testing data
rf_prediction = rf_model.predict( X_test )

# Evaluation Metrics
rf_r2 = r2_score( y_test, rf_prediction )

rf_mae = mean_absolute_error( y_test, rf_prediction )

rf_rmse = np.sqrt( mean_squared_error( y_test, rf_prediction ) )

print("\nRandom Forest Results")
print("R² Score :", rf_r2)
print("MAE :", rf_mae)
print("RMSE :", rf_rmse)


# REGRESSION MODEL COMPARISON
# Create a comparison table for all regression models

regression_results = pd.DataFrame(
    {
        "Model": [
            "Linear Regression",
            "Decision Tree Regressor",
            "Random Forest Regressor"
        ],
        "R² Score": [
            lr_r2,
            dt_r2,
            rf_r2
        ],
        "MAE": [
            lr_mae,
            dt_mae,
            rf_mae
        ],
        "RMSE": [
            lr_rmse,
            dt_rmse,
            rf_rmse
        ]
    }
)

print("\nRegression Model Comparison")
print(regression_results)


# REGRESSION INSIGHTS

print("\nREGRESSION INSIGHTS")

print(
    """
1. Three regression models were evaluated.

2. R² Score indicates how well the model explains revenue variation.

3. MAE measures the average prediction error.

4. RMSE penalizes larger prediction errors more heavily.

5. Random Forest often performs better because it combines multiple decision trees.

6. Feature Importance identifies which business factors most strongly influence revenue.
""")


# SELECT FEATURES FOR CLUSTERING
# Select numerical columns for clustering

cluster_features = df[
    [
        "Revenue_USD_M",
        "Budget_Funding_USD_M",
        "Employees",
        "Launches",
        "Success_Rate_%"
    ]
]

print("\nFeatures Selected For Clustering")

print(cluster_features.head())


# Create StandardScaler object
scaler = StandardScaler()

# Scale all selected features
cluster_scaled = scaler.fit_transform( cluster_features )

print("\nFeatures Successfully Scaled")


# ELBOW METHOD

# Create an empty list to store WCSS values
wcss = []

# Test cluster values from 1 to 10
for k in range(1, 11):

    # Create KMeans model
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    # Train model
    kmeans.fit(cluster_scaled)

    # Store WCSS value
    wcss.append( kmeans.inertia_ )

print("\nWCSS Values")

print(wcss)


# ELBOW CURVE

plt.figure(figsize=(8,5))

plt.plot(
    range(1,11),
    wcss,
    marker="o"
)

plt.title("Elbow Method")

plt.xlabel("Number of Clusters")

plt.ylabel("WCSS")

plt.show()


# KMEANS CLUSTERING
# Create KMeans model

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

# Train model and predict clusters

clusters = kmeans.fit_predict(cluster_scaled)

# Add cluster labels into DataFrame

df["Cluster"] = clusters

print("\nCluster Labels Added")

print(
    df[
        [
            "Company",
            "Cluster"
        ]
    ].head()
)


# SILHOUETTE SCORE
# Calculate Silhouette Score

silhouette = silhouette_score( cluster_scaled,clusters )

print("\nSilhouette Score")

print(silhouette)


# CLUSTER DISTRIBUTION

print("\nCluster Counts")

print( df["Cluster"].value_counts())

# CLUSTER VISUALIZATION

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df,
    x="Budget_Funding_USD_M",
    y="Revenue_USD_M",
    hue="Cluster",
    palette="Set1",
    s=100
)

plt.title("KMeans Clusters")
plt.show()


# CLUSTER CENTERS

print("\nCluster Centers")
print(kmeans.cluster_centers_)


# COMPANIES BY CLUSTER


print("\nCompany and Cluster")

print( df[ [ "Company", "Cluster" ] ].sort_values( by="Cluster") )

# CLUSTERING INSIGHTS


print("\nCLUSTERING INSIGHTS")

print("""
1. KMeans grouped companies with similar characteristics.

2. Companies within the same cluster share similar revenue,
   funding, employee count and launch performance.

3. The Elbow Method was used to determine the optimal number
   of clusters.

4. Silhouette Score measured the quality of clustering.

5. Cluster visualization helps identify high-performing
   and low-performing business groups.

6. These clusters can support strategic decisions,
   benchmarking and market segmentation.
""")


# RANDOM FOREST CLASSIFICATION PERFORMANCE

print("\nRandom Forest Classification Performance")

print(f"Accuracy : {rf_accuracy:.2f}")

print(
    f"Precision : "
    f"{precision_score(y_test, rf_predictions, average='weighted'):.2f}"
)

print(
    f"Recall : "
    f"{recall_score(y_test, rf_predictions, average='weighted'):.2f}"
)

print(
    f"F1 Score : "
    f"{f1_score(y_test, rf_predictions, average='weighted'):.2f}"
)

# RANDOM FOREST REGRESSION PERFORMANCE


print("\nRandom Forest Regression Performance")

print(f"R² Score : {rf_r2:.2f}")

print(f"MAE : {rf_mae:.2f}")

print(f"RMSE : {rf_rmse:.2f}")


# FEATURE IMPORTANCE


# Feature Importance shows which variables contribute the most
# towards the prediction.

importance_df = pd.DataFrame(
    {
        "Feature": X.columns,
        "Importance": rf_model.feature_importances_
    }
)

# Sort features by importance
importance_df = importance_df.sort_values( by="Importance", ascending=False )

print("\nFeature Importance")

print(importance_df)

# FEATURE IMPORTANCE VISUALIZATION

plt.figure(figsize=(10,6))

sns.barplot(
    data=importance_df,
    x="Importance",
    y="Feature"
)

plt.title("Random Forest Feature Importance")

plt.xlabel("Importance Score")

plt.ylabel("Features")

plt.show()

# CLASSIFICATION MODEL COMPARISON


classification_results = pd.DataFrame(
    {
        "Model":
        [
            "Logistic Regression",
            "Decision Tree",
            "KNN",
            "Random Forest"
        ],

        "Accuracy":
        [
            lr_accuracy,
            dt_accuracy,
            knn_accuracy,
            rf_accuracy
        ]
    }
)

print("\nClassification Model Comparison")

print(classification_results)

# REGRESSION MODEL COMPARISON


regression_results = pd.DataFrame(
    {
        "Model":
        [
            "Linear Regression",
            "Decision Tree",
            "Random Forest"
        ],

        "R²":
        [
            lr_r2,
            dt_r2,
            rf_r2
        ],

        "MAE":
        [
            lr_mae,
            dt_mae,
            rf_mae
        ],

        "RMSE":
        [
            lr_rmse,
            dt_rmse,
            rf_rmse
        ]
    }
)

print("\nRegression Model Comparison")

print(regression_results)


# BEST PERFORMING MODELS

best_classification = classification_results.loc[
    classification_results["Accuracy"].idxmax()
]

print("\nBest Classification Model")

print(best_classification)

best_regression = regression_results.loc[
    regression_results["R²"].idxmax()
]

print("\nBest Regression Model")

print(best_regression)


# BUSINESS INSIGHTS
print("\nBUSINESS INSIGHTS")

print("""
1. Companies with higher funding generally generated
   higher revenue.

2. Organizations with more successful launches achieved
   higher success rates.

3. Companies with larger workforces generally produced
   greater revenue.

4. Revenue Per Employee is a useful indicator of
   operational efficiency.

5. Funding Per Employee reflects investment efficiency.

6. Launch Success Ratio indicates launch reliability.

7. Random Forest delivered the best overall prediction
   performance among the evaluated models.

8. KMeans successfully grouped companies with similar
   business characteristics.

9. Feature Importance identified the variables that most
   influenced revenue prediction.

10. This analysis can support business planning,
    investment decisions, and performance benchmarking.
""")

# FINAL CONCLUSION


print("\nPROJECT CONCLUSION")

print("""
This project demonstrated an end-to-end Data Analytics and
Machine Learning workflow using the Space Industry Analytics
dataset (2010–2024).

The project covered:

✓ NumPy for numerical analysis
✓ Pandas for data manipulation
✓ Feature Engineering
✓ GroupBy Analysis
✓ Seaborn visualizations
✓ Classification
✓ Regression
✓ Clustering
✓ Ensemble Learning
✓ Feature Importance
✓ Model Comparison
✓ Business Insights

Among the evaluated models, Random Forest provided the
strongest predictive performance, while KMeans effectively
identified groups of companies with similar characteristics.

Overall, this project shows how Python can be used to extract
business insights, build predictive models, and support
data-driven decision making.
""")





